- name: dummy_env_1

- name: lammps_parse_env
  specifiers:
    lammps_version: 1.2
  setup: |
    conda activate lammps_parse_env
  executables:
    - label: python
      instances:
        - command: python
          num_cores: 1
          parallel_mode: null

- name: lammps_env
  specifiers:
    lammps_version: 1.2
    gcc_version: 3.0231.321+1
  executables:
    - label: lammps
      instances:
        - command: lmp_serial
          num_cores: 1
          parallel_mode: null
