- objective:
    name: dummy_task_1
  inputs:
    - parameter: p1
    - parameter: p2
    - parameter: p5
  outputs:
    - parameter: p3
  actions:
    - environments:
        - scope:
            type: all
          environment: dummy_env_1
      commands:
        - command: Start-Sleep 1

- objective:
    name: dummy_task_2
  inputs:
    - parameter: p3
    - parameter: orientations
  outputs:
    - parameter: p4
  actions:
    - environments:
        - scope:
            type: all
          environment: dummy_env_1
      commands:
        - command: Start-Sleep 1

- version: v2
  objective:
    name: prepare_atoms_box
  inputs:
    - parameter: number_atoms
  outputs:
    - parameter: box
    - parameter: atoms
  actions:
    - environments:
        - scope:
            type: main
          environment:
            name: lammps_parse_env
            lammps_version: 1.2 # a specifier
        - scope:
            type: input_file_generator
          environment: lammps_parse_env
      commands:
        - command: doSomething
- version: v1
  objective:
    name: prepare_atoms_box
  inputs:
    - parameter: number_atoms
  outputs:
    - parameter: box
    - parameter: atoms
  actions:
    - environments:
        - scope:
            type: main
          environment: lammps_parse_env
        - scope:
            type: input_file_generator
          environment: lammps_parse_env
      commands:
        - command: doSomething
- objective:
    name: optimise_atoms
  method: empirical_potential
  inputs:
    - parameter: box
    - parameter: atoms
    - parameter: empirical_potential
  outputs:
    - parameter: optimised_atoms
  actions:
    - environments:
        - scope:
            type: main
          environment:
            name: lammps_env
            lammps_version: 1.2
        - scope:
            type: processing
          environment: lammps_parse_env
      input_files:
        lammps_atoms_file:
          from_inputs: [box, atoms]
        lammps_input_script:
          from_inputs: [empirical_potential]
      outputs:
        optimised_atoms:
          from_files: [lammps_dump_files]
      commands:
        - command: <<executable:lammps>>
          stdin: <<lammps_input_script>>
